### ISSUE TITLE
0x67 Deserialization Errors

### ISSUE THREAD

**Issue by HelloKitty** [HelloKitty/Booma.Proxy#26]
0x67 in pre-library branch is failing deserialization:

This mostly is here for reference as the project migrated to GladNet4 and 4.x of the FreecraftCore.Serializer 

```C# Critical failure. Cannot deserialize File: 0x67_8f3ad515-222a-4859-98bf-4737815e2fc3.packet FileSize: 1332 
    
     Exception: Failed to set member LobbyCharacterData on Type: Booma.Proxy.BlockLobbyJoinEventPayload for Type: BlockLobbyJoinEventPayload Exception: Failed to set member PlayerHeader on Type: Booma.Proxy.CharacterJoinData for Type: CharacterJoinData Exception: Failed to set member unk4 on Type: Booma.Proxy.PlayerInformationHeader for Type: PlayerInformationHeader Exception: Failed to read a desired bytes from the stream. Count: 1314 Position: 1312 Requested: 4... Stack:    at FreecraftCore.Serializer.DefaultMemberSerializationMediator`2.SetMember(TContainingType obj, IWireStreamReaderStrategy source)
       at FreecraftCore.Serializer.ComplexTypeSerializer`1.SetMembersFromReaderData(TType obj, IWireStreamReaderStrategy source)
       at FreecraftCore.Serializer.ComplexTypeSerializerDecorator`1.Read(TComplexType obj, IWireStreamReaderStrategy source)
       at FreecraftCore.Serializer.ComplexTypeSerializerDecorator`1.Read(IWireStreamReaderStrategy source)
       at FreecraftCore.Serializer.SimpleTypeSerializerStrategy`1.FreecraftCore.Serializer.ITypeSerializerStrategy.Read(IWireStreamReaderStrategy source)
       at FreecraftCore.Serializer.KnownTypes.SubComplexTypeSerializerDecorator`1.Read(IWireStreamReaderStrategy source)
       at FreecraftCore.Serializer.SimpleTypeSerializerStrategy`1.FreecraftCore.Serializer.ITypeSerializerStrategy.Read(IWireStreamReaderStrategy source)
       at FreecraftCore.Serializer.SerializerService.Deserialize[TTypeToDeserializeTo](IWireStreamReaderStrategy source)
       at FreecraftCore.Serializer.SerializerService.Deserialize[TTypeToDeserializeTo](Byte[] data)
       at Booma.Proxy.CapturedPacketsTests.Generic_CanDeserialize_CaptureTest[TBasePayloadType](PacketCaptureTestEntry entry) in C:\Users\Glader\Documents\Github\Booma.Proxy\tests\Booma.Proxy.Packets.Tests\UnitTests\CapturedPacketsTests.cs:line 115```

**Comment by HelloKitty** [comment]
See: 0x67_8f3ad515-222a-4859-98bf-4737815e2fc3.packet

**Comment by HelloKitty** [comment]
Duplicate of #23 closing
